package MatApp;


/**
* MatApp/Mat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Mat.idl
* jueves 29 de marzo de 2018 02:28:07 PM VET
*/

public interface Mat extends MatOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Mat
