package MatApp;

/**
* MatApp/MatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Mat.idl
* jueves 29 de marzo de 2018 02:28:07 PM VET
*/

public final class MatHolder implements org.omg.CORBA.portable.Streamable
{
  public MatApp.Mat value = null;

  public MatHolder ()
  {
  }

  public MatHolder (MatApp.Mat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MatApp.MatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MatApp.MatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MatApp.MatHelper.type ();
  }

}
