package MatApp;


/**
* MatApp/MatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Mat.idl
* jueves 29 de marzo de 2018 02:28:07 PM VET
*/

public interface MatOperations 
{
  float suma (float x, float y);
  float resta (float x, float y);
  float multi (float x, float y);
  float divi (float x, float y);
  float potencia (float x, float y);
  float raiz (float x, float y);
  void shutdown ();
} // interface MatOperations
