package MatApp;


/**
* MatApp/MatPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Mat.idl
* jueves 29 de marzo de 2018 02:28:07 PM VET
*/

public abstract class MatPOA extends org.omg.PortableServer.Servant
 implements MatApp.MatOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("suma", new java.lang.Integer (0));
    _methods.put ("resta", new java.lang.Integer (1));
    _methods.put ("multi", new java.lang.Integer (2));
    _methods.put ("divi", new java.lang.Integer (3));
    _methods.put ("potencia", new java.lang.Integer (4));
    _methods.put ("raiz", new java.lang.Integer (5));
    _methods.put ("shutdown", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MatApp/Mat/suma
       {
         float x = in.read_float ();
         float y = in.read_float ();
         float $result = (float)0;
         $result = this.suma (x, y);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 1:  // MatApp/Mat/resta
       {
         float x = in.read_float ();
         float y = in.read_float ();
         float $result = (float)0;
         $result = this.resta (x, y);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 2:  // MatApp/Mat/multi
       {
         float x = in.read_float ();
         float y = in.read_float ();
         float $result = (float)0;
         $result = this.multi (x, y);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // MatApp/Mat/divi
       {
         float x = in.read_float ();
         float y = in.read_float ();
         float $result = (float)0;
         $result = this.divi (x, y);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 4:  // MatApp/Mat/potencia
       {
         float x = in.read_float ();
         float y = in.read_float ();
         float $result = (float)0;
         $result = this.potencia (x, y);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 5:  // MatApp/Mat/raiz
       {
         float x = in.read_float ();
         float y = in.read_float ();
         float $result = (float)0;
         $result = this.raiz (x, y);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 6:  // MatApp/Mat/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MatApp/Mat:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Mat _this() 
  {
    return MatHelper.narrow(
    super._this_object());
  }

  public Mat _this(org.omg.CORBA.ORB orb) 
  {
    return MatHelper.narrow(
    super._this_object(orb));
  }


} // class MatPOA
